package model.network.enums;

/**
 * Server-validated user mutations. Bound to the authenticated session username.
 */
public enum UserCommand {
    ADD_COINS,
    SPEND_COINS,
    ADD_GEMS,
    SPEND_GEMS,
    UNLOCK_PLANT,
    UNLOCK_ZOMBIE,
    UNLOCK_MINI_GAME,
    UPDATE_CHAPTER_PROGRESS,
    UPDATE_HIGHEST_MYOPOINT,
    INCREMENT_GAMES_PLAYED,
    UPDATE_DIFFICULTY,
    ADD_SEED_PACKETS,
    SPEND_SEED_PACKETS,
    ADD_PLANT_FOOD,
    USE_PLANT_FOOD,
    STORE_PLANT_BOOST,
    CONSUME_PLANT_BOOST,
    UNLOCK_GREENHOUSE_POT,
    PLANT_IN_GREENHOUSE,
    HARVEST_GREENHOUSE,
    MARK_NEWS_READ,
    COMPLETE_QUEST,
    PURCHASE_DAILY_DEAL,
    SET_SETTINGS,
    SET_DAILY_OFFER,
    SET_QUEST_PROGRESS,
    PURCHASE_SHOP_ITEM,
    SET_PLANT_LEVEL
}
